config/routes.rb
Rails.application.routes.draw do
  root "billboards#index"
  devise_for :users
  resources :billboards
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/billboard.rb
class Billboard < ApplicationRecord
  belongs_to :user
  
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :song
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :billboard
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_many :billboards, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def handle_flash key, value
    flash[key] = value
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end






end

app/controllers/billboards_controller.rb
class BillboardsController < ApplicationController
  before_action :set_billboard, only: [:show, :edit, :update, :destroy]

  def index
    @billboards = current_user.billboards
  end

  def show
  end

  def new
    @billboard = Billboard.new
  end

  def create
    @billboard = current_user.billboards.new(billboard_params)
    if @billboard.save
      flash[:success] = "Billboard Created"
      redirect_to billboards_path
    else
      flash[:error] = "Error #{@billboard.errors.full_messages.join("\n")}"
      render :new
    end
  end

  def edit
  end

  def update
    if @billboard.update(billboard_params)
      redirect_to billboards_path
    else
      render :edit
    end
  end

  def destroy
    @billboard.destroy
    redirect_to billboards_path
  end

  private
    def billboard_params
      params.require(:billboard).permit(:name)
    end

    
    def set_billboard
      @billboard = current_user.billboards.find(params[:id])
    end

end
  
  

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_song
  
  def new
    @comment = Comment.new
  end
  def create
    @comment = @song.comments.new(comment_params)
    if @comment.save
      redirect_to billboard_song_path(@song.billboard_id, @song)
    else
      render :new
    end
  end

  private
    def set_song
      @song = Song.find(params[:song_id])
    end

    def comment_params
      params.require(:comment).permit(:body, :author)
    end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_billboard
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  def index
    @songs = @billboard.songs
  end

  def show
  end

  def new
    @song = @billboard.songs.new
  end

  def edit
  end

  def create
    @song = @billboard.songs.new(song_params)

    if @song.save
      redirect_to [@billboard, @song]
    else
      render :new
    end
  end

  def update
    if @song.update(song_params)
      redirect_to [@billboard, @song]
    else
      render :edit
    end
  end

  def destroy
    @song.destroy
    redirect_to billboard_songs_path
  end

  private
    def set_billboard
      @billboard = Billboard.find(params[:billboard_id])
    end

    def set_song
      @song = Song.find(params[:id])
    end

    def song_params
      params.require(:song).permit(:title, :artist)
    end
end
 
  
  

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/billboards_helper.rb
module BillboardsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/billboards/_form.html.erb
<%= form_with(model: billboard, local: true, class: "ui form") do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, placeholder: "Name" %>
  </div>
  <br />
  <br />
  <%= f.submit nil, class: "ui button blue" %>
<% end %>

app/views/billboards/edit.html.erb
<h1>Billboards#edit</h1>
<p>Find me in app/views/billboards/edit.html.erb</p>

app/views/billboards/index.html.erb
<h1> Billboard </h1>

<%= button_to "Log Out", destroy_user_session_path, method: :delete %>
<h2>Welcome <%= current_user.first_name %></h2>
<hr />
<%= link_to "Add Billboard", new_billboard_path %>
<h3>Billboard</h3>
<ul>
  <% @billboards.each do |billboard| %>
    <li>
      <%= billboard.name %>
    </li>
  <% end %>
</ul>

app/views/billboards/new.html.erb
<h1>Add Billboard</h1>
<%= form_with(model: @billboard, local: true) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, placeholder: "Name" %>
  </div>
  <%= f.submit %>
<% end %>

app/views/billboards/show.html.erb
<h1>Billboards#show</h1>
<p>Find me in app/views/billboards/show.html.erb</p>

app/views/comments/_comment.html.erb
<hr />
<p>Author: <%= comment.author %></p>
<p><strong><%= comment.body %></strong></p>
<hr/>

app/views/comments/new.html.erb
<h1>Add A comment</h1>
<%= form_with(model: [@song, @comment], local: true, class: "ui form") do |f| %>
  <%= f.label :body %>
  <%= f.text_area :body, required: true %>
  <br />
  <%= f.label :author %>
  <%= f.text_field :author, required: true %>
  <br />
  <br />
  <%= f.submit nil, class: "ui button blue" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BillboardD</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
    
</html>

app/views/songs/_form.html.erb
<h1><%= @song.id ? 'Edit Song' : 'Create Song' %></h1>
<hr />
<%= form_with(model: [@billboard, @song], local: true, class: "ui form") do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, required: true, autofocus: true %>
  <br />
  <%= f.label :artist %>
  <%= f.text_field :artist, required: true %>
  <br />
  <br />
  <%= f.submit nil, class: "ui button" %>
<% end %>

app/views/songs/edit.html.erb
<h1>Edit Song</h1>

<%= render "form", billboard: @billboard, song: @song %>

<%= link_to "Back", billboard_songs_path(@billboard) %>

app/views/songs/index.html.erb
<h1>All Songs on this Chart</h1>
<%= link_to 'Add Song', new_billboard_song_path(@billboard) %> |

<% @songs.each do |song| %>
  <h1><%= song.title %></h1>
    <li><%= link_to song.title, [@billboard, song] %></li> |
<% end %>

<%= link_to 'Back To Billboards', billboard_path(@billboard) %>

app/views/songs/new.html.erb
<h1>Add a Song</h1>

<%= render "form", billboard: @billboard, song: @song %>

<%= link_to "Back", billboard_songs_path(@billboard) %>

app/views/songs/show.html.erb
<h1><%= @billboard.name %></h1>
<h4>Title: <%= @song.title %></h4>
<h4>Artist: <%= @song.artist %></h4>
<br />

<h2>Comments</h2>
<% @song.comments.each do |comment| %>
  <%= render 'comments/comment', { comment: comment } %>
<% end %>
<br />


<%= link_to 'Add Comment', new_song_comment_path(@song), class: "ui button blue" %>
<br />
<br />

<%= link_to 'Edit Song', edit_billboard_song_path([@billboard, @song]) %> |
<%= link_to 'Delete Song', [@billboard, @song], method: :delete %> |
<%= link_to 'Back To Songs', billboard_songs_path(@billboard) %>